### ISSUE TITLE
Use lowercase without spaces for images

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event#100]
The Android app only accepts images that have their name in lowercase and without any spaces.
This is not the case with images right now, so they are not getting displayed when the app is generated from the generator using sample zip file.

**Comment by mariobehling** [comment]
As discussed before this should be solved in the app generator and not be a requirement for the format. The app generator needs to convert them. Thanks for mentioning this blocker again. It is not a bug of the format.
