### ISSUE TITLE
Fix timezone and times of sessions in FOSSASIA sample JSON

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event#103]
The FOSSASIA sample currently shows timezone "UTC" instead of Singapore time in the event JSON (https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/event) and all times of sessions are wrong (https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/sessions), e.g. the grand opening is at 1.30 in the JSON, but it should be at 9.30AM for example. 

The original times are here: http://2016.fossasia.org/schedule/

Please change the times and help to fix the sample.

**Comment by aviaryan** [comment]
@mariobehling Infact, since the timezone is set as UTC in the event json, so technically the time mentioned in sessions json are correct. 
BTW, I agree that it will be more feasible to have the timezone as SGT. I will do it.
