### ISSUE TITLE
Urls for audio files are absolute, make them relative

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event#112]
Url for audio files is given as `/audios/session_37.mp3` , use `audios/session_37.mp3` instead of that , so that they can be used effectively in the webapp.

**Comment by shubham-padia** [comment]
@mariobehling Does this type of change create any issues with orga-server, if not then please merge #113 .

**Comment by aviaryan** [comment]
@shubham-padia yes they will create issues in the orga server.
