### ISSUE TITLE
Test of Open Event Android app on Google IO event

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event#133]
@niranjan94 @mariobehling 
testing the open event android app on google io event and use it to find more improvements we can do to the app part as discussed.

**Comment by niranjan94** [comment]
@arp95 what is this issue about. Please add a proper issue title and description.

**Comment by arp95** [comment]
@niranjan94 
is it fine?

**Comment by mahikaw** [comment]
@arp95 I don't see any issue here. Could you please specify the exact issue, if any, and the steps to reproduce it.

**Comment by mahikaw** [comment]
@arp95 please close this issue now.

**Comment by arp95** [comment]
sure @mahikaw
