### ISSUE TITLE
Convert JSON samples to XML to add support for Giggity app

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event#134]
As Giggity loads xcal/Pentabarf/frab/wafer XML files that contain schedules of conferences. 

I found that conference that has been added is in JSON format. 
But the events in the conference are in [.ics](https://en.wikipedia.org/wiki/ICalendar) file. That is parsed in XML format. A sample events of MOCA 2016 conference is here https://moca.olografix.org/moca2016.ics.

Although events in other conferences are XML format already, e.g., https://static.gnome.org/guadec-2016/schedule.xml.

So if we are going to add the support of our conference to Giggity app I think we should be following their format or we would be asking them to convert the format of other events too that they provide.

I found this information from the previously added [conference](https://github.com/Wilm0r/giggity/pull/2/files) in Giggity. 

I think we should convert our JSON samples to XML and follow their format. 

@mariobehling @the-dagger  @niranjan94

**Comment by niranjan94** [comment]
@heysadboy we already have support for exports in Pentabarf XML, iCalendar (ical) and iCalendar XML (xcal) formats. Please try importing those into Giggity and document what all needs to be added/improved. 

That should be our starting point.

**Comment by niranjan94** [comment]
Create/import an event with a sessions at https://open-event-dev.herokuapp.com and try exporting it.

**Comment by heysadboy** [comment]
@niranjan94 As I could only import an event with sessions created by me so I made this [parser]([url](https://github.com/heysadboy/Giggity-Parser)) to convert the JSON format data of FOSSASIA 2016 into XML format that Giggity can process.

**Comment by heysadboy** [comment]
Closing this as server is able to generate the XML format. We'll be using JSON data in the modified app generated by server.
