### ISSUE TITLE
Adding alternative FOSSASIA 2016 XML sample for Giggity app

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event#139]
Giggity app requires the session details to be in XML format. So we need to add it here to link it in the final JSON file for conference. https://github.com/Wilm0r/giggity .  (See readme)

The XML session file looks like this in my local repo https://github.com/heysadboy/Giggity-Parser/blob/master/Parser/sample.xml .

@niranjan94 @mariobehling @the-dagger

**Comment by niranjan94** [comment]
@heysadboy that looks like the Pentabarf XML format. Open event already supports export to that format. Have you tried the already existing export implementation?

**Comment by heysadboy** [comment]
@niranjan94 It is indeed. I think I could only import the events created by me. I just need to add this here anyways.

**Comment by niranjan94** [comment]
You can import the fossasia 2016 sample under your own name as a new event
and try exporting. The reason I'm asking you to try out the existing export
system is, we want to know what needs to be improved there to support
giggity. Please try that.

**Comment by heysadboy** [comment]
The XML link is provided by server so the files don't need to be added here.
