### ISSUE TITLE
Incorrect Json fields are filled in all samples.

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event#142]
**Actual Behaviour**

The JSON in event.json is storing data in "organiser_description" and "description" fields interchangeably.

**Expected Behaviour**
JSON field "description" should store information about the particular event and "organiser_description" should hold the information about the organiser.

**Screenshots of the issue**

<img width="902" alt="screen shot 2017-05-24 at 11 35 36 am" src="https://cloud.githubusercontent.com/assets/21010060/26388988/349e7578-4075-11e7-822c-e0cad91bbc8f.png">

**Would you like to work on the issue?**
Yes.

**Comment by niranjan94** [comment]
@mahikaw 
So, this issue is about fixing the about us fragment or the samples ? Please be more clear in your description.

**Comment by mahikaw** [comment]
It is for both actually. 

1. We first need to correct the sample so that "description" stores the event description and "organiser_description" stores information about organiser

2. We need to change the string used in about fragment in android app.

Shall I open the same issue in the Android repo too? @niranjan94

**Comment by niranjan94** [comment]
Yes. Please open an issue in the android repo too. And edit this issue description to deal with only the discrepancy in the samples.

**Comment by mahikaw** [comment]
Resolves via #144
