### ISSUE TITLE
Allow more than one track in a session

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event#165]
**Actual Behaviour:**

According to the current API and framework, every session can have only 1 track related to them. 
There are sites/samples where some sessions may have more than 1 tracks/topics related to it. 

**Related information:**

For instance, the F8 event has such sessions : https://www.fbf8.com/schedule/intro-to-building-camera-effects-with-the-ar-platform

**Expected behaviour**

We need to find a way to incorporate such samples too.

**Solution**

I suggest that we make the current "track" object a list of object and display the session under all the tracks in that list.

----

@mariobehling @niranjan94 @the-dagger @mananwason  Please give in your suggestions.

**Comment by niranjan94** [comment]
No @mahikaw . this is not how this should be implemented. A track is different from a topic. A session can have multiple topics but can have only a single track. 

So, until, we implement topics into the server, frontend, API, Spec, we'll just pick one of the topic and use it as a track. 

Closing this issue until our timeline clears up to consider implementation of topics.
