### ISSUE TITLE
Install Frab and research its features and options, compare to Open Event ideas and provide ideas and feedback

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event#17]
http://frab.github.io/frab/
https://github.com/frab/frab

**Comment by rafalkowalski** [comment]
I deployed frab to Heroku. 
http://frab-test.herokuapp.com/
login: admin@example.org
password: test123

I will provide more info when I check it, because this app looks wide.

**Comment by leto** [comment]
This looks like an interesting project to study to see what features they have and what limitations exist. It seems to be a re-implementation of pentabarf in Ruby-on-Rails and does not have a release yet. Their schema is here: https://github.com/frab/frab/blob/master/db/schema.rb Please comment on how it differs from the re-public schema we are planning on using.

**Comment by championswimmer** [comment]
Since we are discussing alternate frameworks with similar goals as
open-event, also check out talkfunnel by HasGeek

https://talkfunnel.com/

HasGeek is a major organisation for tech events in India.
funnel is open source as well (written in python), and has a json API
endpoint
https://github.com/hasgeek/funnel

Funnel does not actually do everything that we aim to, but it does one
important thing for tech events - a forum to submit talk proposals, and a
uniform way to upvote/downvote them.

Take a look at the website, it works pretty good.

**Comment by rafalkowalski** [comment]
I prepared database scheme of Frab app.
http://i.imgur.com/ui0Xh5F.jpg 
Based on it I will describe differences in google doc.

**Comment by leto** [comment]
@rafalkowalski in general, putting things on Github is preferred to google docs

**Comment by rafalkowalski** [comment]
Ok, so I will add it here

**Comment by rafalkowalski** [comment]
@leto Features of Frab App

1. Manage multiple conferences
2. You can assign people to event.
3. You can configure tracks, days, rooms 
4. Drag&drop events onto your schedule
5. You can rate or add a comment to event
6. You can publish schedule of conference(Web app, pdf, html)
7. Checking conflicts between events
8. Reusing people details to another conference
9. Changing colors for event
10. Adding languages 
11. Define conference timezone

In my opinion we have to repair our database. For example events is not connected to anything. I think we need to create Minimum viable product(MVP) which working with basic functionality. First of all we have to define basic features of Opent-event. Then we can expand with new features.

**Comment by leto** [comment]
@rafalkowalski the definition of our MVP is to implement every milestone listed on https://github.com/fossasia/open-event/milestones . The dates are not correct. Please change them to dates that you think are reasonable and fit inside the GSoC timelines
