### ISSUE TITLE
Remove blank lines from Google IO and Spark Event Samples

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event#177]
I tested the app on the Spark and Google IO samples and they don't seem to work. I found that the JSON files are not being read properly by the library used in the web app project. It is declaring it as invalid. After searching around and comparing with other samples for a while, I found that the file contains newline characters which are probably causing the error. I opened the file in gedit with JSON highlighting:

![screenshot from 2017-06-21 10-38-31](https://user-images.githubusercontent.com/8847265/27370914-281f3252-567c-11e7-93ad-2f63504fc55c.png)

 Please fix it. Thank you so much :)

**Comment by Princu7** [comment]
@arp95 Hi. There are some still blank lines removing due to which the generation of the app is failing. Please look into it. Thanks :)

**Comment by arp95** [comment]
@Princu7 
the google io is working fine right?
spark one i will work when google io is merged.
