### ISSUE TITLE
check talkfunnel by hasgeek, and discuss if we can include that in the orga server or implement similar functionality

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event#18]
Since we are discussing alternate frameworks with similar goals as open-event, also check out talkfunnel by HasGeek

https://talkfunnel.com/

HasGeek is a major organisation for tech events in India.
funnel is open source as well (written in python), and has a json API endpoint
https://github.com/hasgeek/funnel

Funnel does not actually do everything that we aim to, but it does one important thing for tech events - a forum to submit talk proposals, and a uniform way to upvote/downvote them.

Take a look at the website, it works pretty good.

**Comment by championswimmer** [comment]
I think, maybe if we can achive our preliminary project goals by mid-term, we can look at including funnel functionality on orga server. 
What say guys ?

**Comment by leto** [comment]
@championswimmer we already have a plan for using the schema that gives us interoperability. Let's not change plans mid-stream. I have assigned this issue to @rafalkowalski so he can give us a quick summary of what talkfunnel can do and if it has ideas/features worth borrowing. Don't spend more than 1 hour on this task. Add your findings as a comment here.

**Comment by championswimmer** [comment]
I wasn't refering to changing schema. I was wondering if we would like to
add the functionality of a talk proposal upvote/downvote system in our
project (maybe in future).
If/when we implement it, we'll do it with a schema that is compatible with
our existing one

**Comment by leto** [comment]
@championswimmer upvote/downvote sounds nice, but it is not a core feature. Let's implement core features first. That sounds like a great addition to add after GSoC is over :smiling_imp:

**Comment by rafalkowalski** [comment]
@championswimmer I have problem with installation funnel. Could you help me with it?

**Comment by rafalkowalski** [comment]
We can use such a view https://rootconf.talkfunnel.com/2015/schedule to present schedule. It looks great :)
