### ISSUE TITLE
Issues in the All of Hands 2016 Sample

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event#182]
Currently, we are not able to generate a web app out of the All of Hands 2016 sample. It gave an invalid JSON error. After searching for the issue for a while, it seems there are some typos. Some quotes are not properly closed. Like in this screenshot:-

![screenshot from 2017-06-22 07-21-06](https://user-images.githubusercontent.com/8847265/27413832-6841bf22-571b-11e7-9e2e-10dd8d7c31d3.png)

The quotes in the LinkedIn field is not closed. Also, the images are not present in the sample. Please look at these issues. Thanks :)

**Comment by mahikaw** [comment]
@Princu7 Yes I had fixed these locally but it still doesn't work. I am fixing it currently 👍

**Comment by mahikaw** [comment]
Resolved via #183 @Princu7 You can close this issue now 👍
