### ISSUE TITLE
Updating MozillaAllHands16

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event#184]
The current sample is incomplete in various aspects.

- [ ] Missing sessions and speakers need to be added.

- [ ] Images of some speakers along with their descriptions and sites need to be added.

**Comment by niranjan94** [comment]
> The current sample is incomplete in various aspects

@mahikaw very vague. please list out the parts that are incomplete

**Comment by Princu7** [comment]
Please see  the following issues 

*  Some of the dates are in incorrect format. Like one of them is mentioned like this 2016-12-09T017:00:00 which is incorrect.
*  Also, the event dates are from 05 to 09 but some sessions have their timing on 10 which is wrong.

Please correct them so they can be included on the showcase site.

**Comment by mdew192837** [comment]
Where is the official history of the event? I can't seem to find it.

**Comment by invinciblycool** [comment]
Opened a PR.
Let me know if any corrections are needed.
