### ISSUE TITLE
Project Planning - Org Server, Web app, Android App

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event#19]
Based on the work we have done so far, we have come up with a way to separate projects we would like you to work on now. I have tried to sum up different discussions. Please have a look at the following and give feedback and input. @leto Please confirm the following separation as well.

Project 1 (Rafal): Python Backend/Frontend -- https://github.com/fossasia/open-event-orga-server -- Open Event Organiser Web Client https://github.com/fossasia/open-event-orga-webclient

Project 2 (championswimmer): Web App -- https://github.com/fossasia/open-event-webapp

Project 3 (Manan): Android App (newly developed) -- https://github.com/fossasia/open-event-android

Does this work for you? Please start to work on your project by writing down a list of features and then adding issues with the respective labels. 

While you focus on different areas, we still hope to see continuous cooperation among each other and support across the different projects.

**Comment by rafalkowalski** [comment]
Was there any discussion about Opent Event Organiser Web Client? Or Could someone tell me about requirements in this project?

**Comment by mariobehling** [comment]
@rafalkowalski https://github.com/fossasia/open-event/blob/master/README.md

**Comment by leto** [comment]
Yes, I think this is a good plan moving forward @mariobehling . Since all the GSoC projects are really a "constellation" of projects that interact, we expect that there will be a lot of communication across the projects, such as reporting bugs, giving code reviews and testing releases.

The project assignments above are what your GSoC mid-term and final will be based on, so make sure you are working on your own project primarily!

**Comment by championswimmer** [comment]
Do we need the webclient?  Because the orga server as of now is providing a
front end already.

**Comment by mariobehling** [comment]
Good question. @leto How about the separate repo for the web client? 

@championswimmer: I made a mistake in the first post in this issue. The repo for your project is as follows. 

Project 2 (championswimmer): Web App -- https://github.com/fossasia/open-event-webapp

Sorry for the confusion. Corrected it above as well.

**Comment by leto** [comment]
@mariobehling Yes, since the orga-server repo will have a Flask-Admin front-end, I don't think we will need another repo for the web client.

**Comment by championswimmer** [comment]
I have a suggestion/request here. Right now the API is volatile, and both
api and schema might change rapidly. Also the Android app has no
frontend/gui at all. We need to crystallise the features for gui, and then
we'll reach at an MVP stage where we have a stable v1 api, and a basic idea
of how the app looks and functions.
So could I work with Manan, on the App, so that we quickly reach this stage
(ie where we can generate usable apps with features comparable to the
FOSSASIA companion app at least) , and after that I start working on the
webapp, because it'll be easier to have the android app as a reference to
model the ui of web app upon.

**Comment by mariobehling** [comment]
@championswimmer Interesting proposal. In order to better understand which way we can head with the mobile apps, it would be good to do some more research and see what other apps are offering. I created a separate issue for this. Please help https://github.com/fossasia/open-event/issues/20

**Comment by rafalkowalski** [comment]
@championswimmer Maybe I can help you somehow in android or webapp?

**Comment by mariobehling** [comment]
@championswimmer @rafalkowalski Great spirit of collaboration! We definitely want cooperation and support, but we also need each part to function and we need one of you to take the main responsibility for each area. So, yes, let's work together on different areas, but please help to get each component in place.

Please create a list of features for the components here now: https://github.com/fossasia/open-event/blob/master/FEATURE.md
Thank you.

**Comment by rafalkowalski** [comment]
@mariobehling I think we need code review. Because each of us have different experience, so it would be nice to share experience how to improve parts of code.

**Comment by mariobehling** [comment]
sure, code review is definitely necessary. Duke and Mohit are already supporting us here. For now the focus is to get the feature list. And then based on this llist create issues. After we have a list of tasks, it will be more structured for everyone. Please help to get the feature list ready.

**Comment by leto** [comment]
@rafalkowalski if you want a code review, send an email to the list with a link to Github and ask direct and detailed questions.

**Comment by mariobehling** [comment]
@championswimmer 

> We need to crystallise the features for gui, and then we'll reach at an MVP stage where we have a stable v1 api, and a basic idea of how the app looks and functions. So could I work with Manan, on the App, so that we quickly reach this stage (ie where we can generate usable apps with features comparable to the FOSSASIA companion app at least) , and after that I start working on the webapp, because it'll be easier to have the android app as a reference to model the ui of web app upon.

Yes, we also recognize this question about UI etc., but we have clearly two different projects and the web app has a high priority.

A clear feature list and well-designed mockups would be great. I had assigned https://github.com/fossasia/open-event-webapp/issues/1 to you 16 days ago and was hoping to get some info on how this web app can be designed and what technologies to use.

Please help us here and show us what is your plan for the web app: https://github.com/fossasia/open-event/issues/24

We want cooperation, but two students working randomly on the same thing does not make sense.
