### ISSUE TITLE
change all the conflicting attribute names of new api with old api

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event#190]
Will be changing all the conflicting attribute names of all samples merged till now which have conflciting attribute names.

All of the attribute names of new api which have conflicts with the old api are given in these docs:
https://docs.google.com/document/d/1caaCeOOTIxQn2HR1Uj9r-cHXQH5hSYzzzCJpt3rkl38/edit

**Comment by arp95** [comment]
@Princu7 
can you please confirm the script of models over here:
https://github.com/arp95/script_for_samples

so that i can send a pr for all samples at once then.
Thanks!

**Comment by arp95** [comment]
@iamareebjamal @Shailesh351 @shreyasnbhat @rohanagarwal94 
can you guys please review my script so that all the samples be updated at one go instead of individually reviewing them?

Link: https://github.com/arp95/script_for_samples

**Comment by iamareebjamal** [comment]
@arp95 It'll be really easy if you just map the old and new attributes one to one using a tuple or dict and perform all these operations in a loop instead of manually repeating same tasks

**Comment by arp95** [comment]
yes @iamareebjamal that would be good.
but as the scripts are already made dont you think it is better to see them like this.
