### ISSUE TITLE
Please propose a process for testing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event#2]
How should we test the app? Currently, I see, that I receive a message "Done", but then it does not work or is wrong, e.g. instead of May 14, I see May 13, May 14, May 15 in the app. These are small things and should be first tested by the developer. How do you suggest to improve the testing?

**Comment by mananwason** [comment]
I'm sorry @mariobehling , I didn't know that the event is only on the 14th, hence the mistake. 
One thing we can do for testing is inserting screenshots before committing changes, so that everyone else can point out mistakes, if any.

**Comment by mariobehling** [comment]
@rafalkowalski @championswimmer How can we keep up the speed and quality? What are your suggestions?

**Comment by championswimmer** [comment]
Partly can be helped with setting up Travis. It checks the basic build
errors, if any, and also generates apks on tags, so everybody can download
and check.

For reference check https://github.com/teamOSC/LearnHut_android/releases
(and this is the travis config
https://github.com/teamOSC/LearnHut_android/blob/master/.travis.yml)

**Comment by mariobehling** [comment]
@championswimmer Could you help to get started with travis for the OpenTechSummit app, please?

**Comment by championswimmer** [comment]
Sure

**Comment by championswimmer** [comment]
Done, every push will be tested by travis now. The build status badge is placed in README. 

Also to generate release apk, we need to make a tag. Remember to push tag first, before pushing branch.

``` 
git commit; 
git tag 0.0.1; 
git push origin --tags; 
git push origin master;
```

**Comment by rafalkowalski** [comment]
I think it's good idea to make tasks in different branch. Branch should be named as issue(rp-1). Every person after finishing issue should assign person who will be responsible for review code. After positive review, branch can be merged with master. I assume that everyone ought to check new functionality on his own  before sending it to reviewer(simple cases). Besides every function should be covered by test.

**Comment by leto** [comment]
Yes, each feature should get it's own branch. Feel free to give the branches more intuitive names that include the issue number, like "issue15/fix_json" so it is clear from the branch name what it is for.

There a a few different kinds of tests. We can benefit from unit tests on the low-level functions, integration tests for the API and acceptance tests that are higher level and verify that a feature works correctly. The goal is the automate as much as possible while documenting what is not currently automated so it can be done manually and hopefully automated in the future.
