### ISSUE TITLE
Research existing mobile event apps and compare them

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event#20]
What mobile event apps exist on the app markets, github etc.? What are their advantages and disadvantages? Please provide links and screenshots.

**Comment by mananwason** [comment]
@mariobehling The best app has to be hands down the google io app. Here is the source code https://github.com/google/iosched
Take a look at it from the play store link given above. It's the 2015 app on the store.

**Comment by mariobehling** [comment]
@mananwason Thanks. 
If you say "the best app", with which other apps did you compare? Please list other apps as well. Cheers.

**Comment by mananwason** [comment]
@mariobehling I have seen 2-3 apps other than io and fosdem/fossasia. They are not so good.
One is giggity. Others:-linuxday Cagliari and some event guide apps like london official events guide. So bottom line is Google's io app is the best of the lot. I would report if I see some other apps which are good.
Sorry, I can't provide you with links, I am on a mobile device. Thanks.

**Comment by rafalkowalski** [comment]
I found disccussion about events app:
http://www.quora.com/Mobile-Applications/What-are-the-best-mobile-event-apps-for-conferences-and-corporate-events

Guidbook looks nice: https://guidebook.com/

**Comment by mananwason** [comment]
Nice work @rafalkowalski. This list looks good
