### ISSUE TITLE
Update all the samples according to the new API specifications [ On Hold ]

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event#205]
The samples in the repo have become inconsistent. [Mozilla All Hands 2017](https://github.com/fossasia/open-event/pull/191/files) and [FOSSASIA 2016](https://github.com/fossasia/open-event/commit/77783374aca8b9cc2849484564dbd9cab54aff37) are using the new attributes as defined by the new API specifications while the other events are using the old attributes. Since we are removing support for the old attributes from the web and Android generators too, it would be good to convert all the remaining samples too according to the new API specs. Otherwise, a part of the samples (either old or new) won't be working anymore. Please suggest. Thanks :)
@mariobehling @niranjan94 @aayusharora @Shailesh351

**Comment by mariobehling** [comment]
Please ensure you take all samples into account:
* Droidcon17	
* EhealthAfrica	
* FBF817	
* FOSSASIA10	
* FOSSASIA11	
* FOSSASIA14	
* FOSSASIA15	
* FOSSASIA16
* GoogleIO17	
* MozillaAllHands16	
* MozillaAllHands17	
* OSCON17
* OTS16
* PyCon17	
* RedHatSummit17
* SparkSummit17

**Comment by mariobehling** [comment]
But: You can delete Ehealth Africa. No need anymore.

**Comment by Princu7** [comment]
On further thought, updating the samples right now would not be a good choice. It's because we still haven't completely migrated to the new API. Some of the events like NextCloud Conf are still on the old server and use the outdated attributes. So, if we update the samples and don't keep support for the old attributes, then the NextCloud Conf won't work and we won't be able to generate it. What we can do is revert the PRs which update the samples and then after we have completely migrated to the new API, we can update all the samples then with the help of sample scripts.
