### ISSUE TITLE
Feature List and Project Plan for Orga Backend/Frontend (2015)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event#22]
Please define the following for your project
a) Feature List (add it to Feature.md)
b) Project Plan with possible milestones (Which features will be implemented at what time)
Proposed Milestones
* Milestone 1, Due by June 10, 2015
* Milestone 2, Due by June 26, 2015
* Milestone 3, Due by July 25, 2015
* Milestone 4, Due by August 21, 2015 

> Project 1 (Rafal): Python Backend/Frontend -- https://github.com/fossasia/open-event-orga-server -- Open Event Organiser Web Client https://github.com/fossasia/open-event-orga-webclient
Also refer to #19

**Comment by rafalkowalski** [comment]
Milestone 1
- Create App based on Flask
- Database configuration
- Prepare admin panel based on flask-admin
- Prepare Crud methods for models
  1. Session
  2. Event 
  3. Sponsor
  4. Track
  5. Microlocation
  6. Speaker
- Provides Api:  Session, Event, Sponsor, Track, Microlocation, Speaker, Configuration
- help others
Milestone 2:
- Possibility to attach files(e.g. images)
- Admin Panel View improvements
- Testing
- Writing documentation

**Comment by mariobehling** [comment]
@rafalkowalski Good start. What features do you see in frab to organize events in tracks? Is this covered by crud methods? Which roles do you define?

**Comment by rafalkowalski** [comment]
@mariobehling Maybe It will be good idea to have two roles(Speaker, Admin). On the main page you will have two choices to sign in. Of course both of these roles will have different permissions. 

Frab have only possibility to assign event to Track via form, so it's covered by crud methods.

I like frab schedule , because you can drag&drop events. Perhaps this feature will require a lot of workload

**Comment by mariobehling** [comment]
@rafalkowalski This is a focused proposal and I am eager to read more in detail in the issues you are creating in the respective repo.

How about design of the UI (mockups, wireframes)? We do not have a designer, so this needs to be part of the project as well.

Apart from that: How will you do the documentation? What are your plans here?

**Comment by championswimmer** [comment]
Closing this, as this was for GSOC 2015. We need to create new roadmap for 2016 and future
