### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/open-event#220]
Currently website is down http://open-event-dev.herokuapp.com/
Screenshot:
![image](https://user-images.githubusercontent.com/8705386/31017093-e726ed46-a516-11e7-854a-f5321d2c8ff8.png)

**Yes, I would like to work on this issue**

**Comment by shubham-padia** [comment]
Duplicate of https://github.com/fossasia/open-event-orga-server/issues/4497, there are people already working on that :smile:
