### ISSUE TITLE
Displaying a message after upload completes.

### ISSUE THREAD

**Issue by invinciblycool** [fossasia/open-event#224]
As of now no message is displayed upon completion of an upload of a zip.
It would be better, if a message is displayed maybe saying "Upload complete" to ensure that the upload has been finished and the button to Generate Webapp can be clicked.

**Comment by shubham-padia** [comment]
@open-event-bot move to fossasia/open-event-webapp

**Comment by shubham-padia** [comment]
Please open the issue in fossasia/open-event-webapp repository

**Comment by invinciblycool** [comment]
Okay
