### ISSUE TITLE
Repository size too large.

### ISSUE THREAD

**Issue by agbilotia1998** [fossasia/open-event#234]
Due to media files of various samples in this repository , the repository size have become around 700 MBs.
It becomes hard to clone and git pull or git fetch.

Fix: We can reduce the size of the media files. Or any such changes that we just put the zip files of the samples in this repository and change our app generation mechanism such that we provide it the url of the zip file of the sample,  it downloads it from that url and uploads it.

Because as of now there are only few samples if the number increases the size of repository would become too large.

@mariobehling  @geekyd thoughts?

**Comment by agbilotia1998** [comment]
@mariobehling I think we should create separate repository for each sample.

**Comment by shubham-padia** [comment]
@mariobehling Instead of keeping all the sample and the zips in a single repository, a better option would be to move all the samples in their individual repositories. The only samples in the current repo would then be the the recent fossasia summits. URL to the individual repos can be kept in a seperate json in this repository for access to the open-event-webapp.

**Comment by geekyd** [comment]
Great suggestion by @shubham-padia distributing samples seems a good solution here. In addition to that we can compress the media files and reduce their size.

**Comment by mariobehling** [comment]
This is valid, but it will make it difficult to follow up and disperse attention. Compressing the media files is probably the best approach as a first step. However, there need to be some changes when we generate a web app with the media files and I want to focus on this later. I think a priority in Open Event is to get the front-end ready before we focus on other things. Therefore I am closing this for now.
