### ISSUE TITLE
Create an updated sample for the FOSSASIA Summits 2014 and 2015 as a zip and generated a sample website

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event#239]
Please create an updated sample for the FOSSASIA Summits 2014 and 2015 as a zip and generated a sample website using https://webgen.eventyay.com/. Debug any issues and deploy the sample website on your own Github Pages.

Current error for the samples is: 

`ERROR:Invalid ZipKnow More
TypeError: Cannot read property 'photo-url' of undefined`

**Comment by marvin08** [comment]
@mariobehling I want to work on this.

**Comment by agbilotia1998** [comment]
We can create websites for these samples once PR to support Old APIs gets merged.

**Comment by ParthS007** [comment]
working on it with @agbilotia1998  👍

**Comment by 0x48piraj** [comment]
@mariobehling You have closed the Issue, and a GCI Task Instance is pointing to this issue. What to do ?
