### ISSUE TITLE
Feature List and Project Plan for Web App (2015)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event#24]
Please define the following for your project
a) Feature List (add it to Feature.md)
b) Project Plan with possible milestones (Which features will be implemented at what time)
c) Technologies used

Proposed Milestones
* Milestone 1, Due by June 10, 2015
* Milestone 2, Due by June 26, 2015
* Milestone 3, Due by July 25, 2015
* Milestone 4, Due by August 21, 2015 

> Project 2 (championswimmer): Web App -- https://github.com/fossasia/open-event-webapp
Also refer to https://github.com/fossasia/open-event/issues/19

**Comment by championswimmer** [comment]
In light of this https://github.com/fossasia/open-event-webapp/milestones
and this https://github.com/fossasia/open-event-webapp/blob/master/README.md

can we close this issue ? 

The readme and features will become more detailed as I keep working on this further

**Comment by mariobehling** [comment]
@championswimmer Honestly, it would be really good you add the details here in this issue. So we all have a reference overview. Please do not close this issue until the project is finished. Continue to add additional features and changes to the plan here, please. Be inspired by Rafal: https://github.com/fossasia/open-event/issues/22

**Comment by championswimmer** [comment]
Ok, I'll add the details here. 

**Features**
Refer here - https://github.com/fossasia/open-event/blob/master/FEATURE.md#open-event-webapp

**Milestones**
Milestone 1, Due by June 10, 2015
 * Basic layout of webapp
 * Add views for Sessions, Speakers, Tracks,
 * Show basic data from API (title, summary etc) in a list, in above views

Milestone 2, Due by June 26, 2015
 * Finish the theme (simple, flat UI, made using Bootstrap) 
 * Responsive layouts, supporting various screen sizes
 * Write and enable test cases

Milestone 3, Due by July 25, 2015
 * Improve UI, pop-up dialogs for extended Session details, more details about speakers etc
 * Package as a crx (Chrome extension)
 * Try to port to various mobile OSs using Ionic framework

Milestone 4, Due by August 21, 2015 

**Technologies**
 * AngularJS 
 * Bootstrap

**Comment by mariobehling** [comment]
@championswimmer You are aware, that we need this app to be generic (e.g. different colors, logo etc.) to work for different events as well, correct? What way do you think works best? Can the app be generated by a script or how should the process work here? 
The original idea is that people can set up the web app on their server. Is that the best solution? Or do we offer to set up the app as a service on our own server? 

Secondly, please keep in mind the integration of the twitter wall https://github.com/fossasia/open-event/issues/6

**Comment by championswimmer** [comment]
I'm thinking of making a config.json file, which will contain the
replaceable portions (color codes, api endpoints etc).

And yes, best solution would be for people to host it. Ideally, it can be
hosted on a Github repo, as this will have only client side code.
I will aim to make it such that people can fork our repo, and change only
the config.json, and be able to host it via github pages. Does that sound
good ?

Yes, I have had experience with twitter using js fortunately. Making the
twitter wall would be easy for me :)

**Comment by mariobehling** [comment]
@championswimmer Sounds like a good start for a plan to me. Could you add details about your idea to the milestones, please? The idea is: Every feature should be a bullet point in the milestones. 

Having more info here, would also make it easier to give more input and having documentation we can go back to and look it up.

Regarding the twitter wall, please check out what the loklak team is doing, when you look at this feature: https://gitter.im/loklak and https://github.com/loklak

**Comment by leto** [comment]
@championswimmer I strongly recommend that vagrant is used so that anybody can spin up a local copy of the web app or deploy it to any service, not just Heroku. You can use the one that @rafalkowalski worked on here https://github.com/fossasia/open-event-orga-server/blob/master/Vagrantfile . Please ask me questions if there are things you don't understand and add bullets to your plan about vagrant.

**Comment by championswimmer** [comment]
For only client side, why would I need a container.

Any browser can open it on any filesystem. Regardless of OS and env.

Like gh-pages looks like best option to me to host it. No deployment needed
at all. The code is the product itself.

**Comment by leto** [comment]
@championswimmer I assumed that you were going to use some JS/CSS/other pre-processors which would require installing dependencies. If that is not the case, and you don't need to compile anything, then vagrant is not needed.

**Comment by championswimmer** [comment]
I am trying to avoid any compilation. Should make it easier for the organization to deploy it. If I end up having to depend on some compilation process, I'll use vagrant :)

**Comment by leto** [comment]
@championswimmer sounds like a plan! I like simplicity.

**Comment by championswimmer** [comment]
Closing this, as this was for GSOC 2015. We need to create new roadmap for 2016 and future
