### ISSUE TITLE
How can we change colors from data retrieved from orga server ?

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event#25]
I searched on the internet, but couldn't find a satisfactory answer, Please suggest @championswimmer  if we can even do this because most of the answers online suggest otherwise.

**Comment by leto** [comment]
What does this mean? Which repo and code are you talking about?

Can you point to exact lines of code that you tried and does not work?

Did you try to write some code? Please be more specific when opening issues and link to references.

**Comment by mananwason** [comment]
@leto I was trying to get the android app theme colors from the orga server and then set it dynamically in the java code instead of in xml, so that we don't need to hardcode colors for the app. I haven't 
I did write some code towards this objective but nothing worked, hence I didn't commit it .  So, I was looking for suggestions.

**Comment by leto** [comment]
@mananwason in the future, commit the code that you try and then ask us why it does not work. That is how you will learn. To restart, please try some new code or commit something that you tried that may work and we will help you figure it out. That is the whole point of GSoC. For you to write code and for us to review it and help you make it better.

**Comment by mariobehling** [comment]
@mananwason Which code or solution did you try, that did not work? Links to stuff that you researched? This could save others time who might come across the same difficulties.

Please be specific: What did you try exactly?

**Comment by rafalkowalski** [comment]
@mananwason If something doesn't work, you can create new branch and We can see it :)

**Comment by rafalkowalski** [comment]
@mananwason Maybe here, you can find a solution
http://stackoverflow.com/questions/3241729/android-dynamically-change-style-at-runtime

**Comment by mananwason** [comment]
@leto @mariobehling @rafalkowalski I was saying that there was a limitation in android which doesn't allow us to change colors on runtime. I followed these links but these don't fulfil our purpose
https://teamtreehouse.com/forum/dynamically-changing-background-color-android-java
http://stackoverflow.com/questions/25815769/how-to-really-programmatically-change-primary-and-accent-color-in-android-loll
But anyway I got the answer, there is a library https://github.com/negusoft/GreenMatter which does the same.
But one question is that, is it necessary as we will have to bump the minimum sdk version to 14, if we use this library and this library is in testing phase. Please Suggest.

**Comment by championswimmer** [comment]
Let's keep this aside for now. Dynamic changes can be done, I have
experience with it. Let's focus on getting data and showing it here and get
minimum required functionality.

Things that need to be changed for each event's app can be put in
res/values/config.xml and that xml can be generated during customisation of
the app (for now). Ideally, in the final product, yes, everything other
than package name of app should come from the api.

**Comment by rafalkowalski** [comment]
@championswimmer What data should I provide you with configuration? Gui color, conference logo, event title, event email and something else?

**Comment by mananwason** [comment]
I don't think logo can be acquired from api and then displayed, because it has to be fixed for the app.

**Comment by mariobehling** [comment]
@rafalkowalski @mananwason If logo can be acquired from Api it would be great. Flexibility of all components is highly desired.

**Comment by championswimmer** [comment]
Logo can be acquired from API, but only after first internet connection.
First time logo has to be fixed.

**Comment by mananwason** [comment]
@championswimmer Please see this 
http://stackoverflow.com/questions/21108611/how-can-we-change-android-application-icon-dynamically-in-android
