### ISSUE TITLE
Change Fossasia samples to FOSSASIA Summit 

### ISSUE THREAD

**Issue by ParthS007** [fossasia/open-event#256]
The Fossasia samples and overview page should use FOSSASIA Summit as text.

**Comment by ParthS007** [comment]
In reference to https://github.com/fossasia/open-event-webapp/issues/1610

**Comment by duttaditya18** [comment]
@ParthS007 Can you tell me in detail what needs to be done?

**Comment by 0x48piraj** [comment]
Close this @ParthS007 
You solved this issue :100:
