### ISSUE TITLE
Update the hosted server with changes made recently

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event#26]
@championswimmer please update the server.

**Comment by leto** [comment]
We need a better way than this. @championswimmer can you set up a cron job to update the latest changes from master? I strongly recommend creating repository on the server dedicated to this, which is separate from your dev repo on that server. Please ask specific questions about setting that up if it is not clear

**Comment by championswimmer** [comment]
I'll set up the cron job. A 1 hour cron is justified I hope ? 

The repos are different already, deploy dir and dev dir are separate.

**Comment by leto** [comment]
@championswimmer once per minute would be better :smiling_imp:

**Comment by championswimmer** [comment]
No way :D , there's stuff that runs on my server :P Limited bw, disk usage.
I'll make it 5 minutes.

**Comment by rafalkowalski** [comment]
@championswimmer I think , it should but maybe good idea is to create dummy data via script in python

**Comment by mananwason** [comment]
@championswimmer Please make it running. I need to test the code I have written and I am just stuck here till I test it. 
Thanks.

**Comment by rafalkowalski** [comment]
I think everyone shoud have access to server

**Comment by mariobehling** [comment]
@championswimmer @mananwason @rafalkowalski Could you discuss this on the chat? Seems like a better option.

**Comment by mananwason** [comment]
+1 @rafalkowalski . I also second @leto becuase if we change data while an event is going on, 5 mins is an awfully long time. We should keep it as low as possible.

**Comment by mananwason** [comment]
Sure @mariobehling

**Comment by creativepsyco** [comment]
@mananwason you perhaps mock out the API implementation on the client in
Debug mode so that you don't have to depend on Server, you can hard code
JSON replies or use JSON files bundled together. See
https://github.com/square/retrofit/blob/master/samples/src/main/java/com/example/retrofit/SimpleMockService.java

**Comment by championswimmer** [comment]
Made a 1 min cronjob

The cron does NOT delete the app.db (or else we would have a blank slate every 1 min). 
There should be a button on the admin console to refresh the database. Or else whenever app.db needs deleting, I'll have to do manually via ssh.
