### ISSUE TITLE
Can't create records due to Read only permission

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event#27]
@championswimmer Please provide write permissions.

![untitled](https://cloud.githubusercontent.com/assets/10570249/7834716/aa5d7b70-048f-11e5-8ffd-555c01d338fe.jpg)

**Comment by championswimmer** [comment]
I fixed the permission, but this error occurs now 
```
Failed to create record. (pysqlite2.dbapi2.OperationalError) unable to open database file [SQL: u'INSERT INTO tracks (name, description) VALUES (?, ?)'] [parameters: (u'Android', u'All about Android')] 
```

Not sure exactly how to fix this

**Comment by mananwason** [comment]
Yeah exactly, so maybe @rafalkowalski can help.

**Comment by mananwason** [comment]
According to http://stackoverflow.com/questions/7670289/sqlite3-operationalerror-unable-to-open-database-file , you need to change permissions of the folder containing the file. Please give it a try.

**Comment by rafalkowalski** [comment]
I deployed to Heroku You should use this site http://glacial-earth-2730.herokuapp.com/admin/
