### ISSUE TITLE
What is the best way to store event data? What standards and formats exist, e.g. ical, xml, json etc.?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event#3]

**Comment by championswimmer** [comment]
Imo, best way to store data would be json.

Ideally, for static data based apps, I prefer keeping a json in the assets
folder from which the app loads. If there is network connectivity app
checks server for newer version of json, and if found, downloads and shows
data from it.

**Comment by creativepsyco** [comment]
Here's the Google Format for their IO 2014 application: https://github.com/google/iosched/blob/master/doc/SYNC.md Mostly a collection of several different entities `speaker`, `session`, `company`, `map`, `category`, `tag` etc

**Comment by rafalkowalski** [comment]
I've worked only with JSON, so I think it's good idea to store data as json.

**Comment by leto** [comment]
I think we can all agree that we are not going to drastically change our conventions and that we will be using a JSON file stored on Github. I will leave it to @mariobehling to close this.
