### ISSUE TITLE
need to add support for format level and language tables and endpoints

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event#30]
@rafalkowalski has to implement this on the server,
 and then @championswimmer and @mananwason have to implement the respective client apps. 

https://github.com/opendatacity/re-data/blob/master/doc/api.md#get-eventsevent-idlanguages
https://github.com/opendatacity/re-data/blob/master/doc/api.md#get-eventsevent-idlevels
https://github.com/opendatacity/re-data/blob/master/doc/api.md#get-eventsevent-idformats

Need to add support for the above

**Comment by rafalkowalski** [comment]
@mananwason @championswimmer I deployed it to http://open-event.herokuapp.com/admin/
I can deploy all to Oceandigital server, but i have to drop database, because i made a lot of database changes. Can i drop database on Arnav server? Then I will run re:data script to fill data

**Comment by championswimmer** [comment]
yes sure go ahead

**Comment by mananwason** [comment]
yeah sure. Go ahead

**Comment by rafalkowalski** [comment]
http://springboard.championswimmer.in/api/v1/event/1 link changed @championswimmer @mananwason
