### ISSUE TITLE
Get Open Event ready for OpenTechSummit 2016 

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event#35]
Opentechsummit is coming on 5th may. We need to improve the app and the parser to make it ready for the  event. @mariobehling can you provide some pointers for the api or the spreadsheet where we can get the data from? 

* [ ] Improve the spreadsheet parser written [here](https://github.com/fossasia/open-event-orga-server/tree/master/open_event/tools/fossasia)
* [ ] Fix current bugs in android app
* [ ] Fix event editing rights for the server
* [ ] Work on the iOS app as well to get some detailed info. Right now it shows pretty basic info.

**Comment by the-dagger** [comment]
@mananwason the android app is pretty much ready IMO, so we can move towards modifying the app so as to work well with the newer APIs and testing it in the process too.
What do you say?
Cheers.

**Comment by mananwason** [comment]
@the-dagger There are still some things we need to fix. I'll be getting a list ready so that we can start working on them. First we need to fix the spreadsheet parser. Please report bugs you find in the parser. Cheers!

**Comment by the-dagger** [comment]
Ok, sure.
I'll be having a look at the parser as soon as i get home.
Cheers.
