### ISSUE TITLE
How can we generate a generic app, that can be used for different events?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event#4]
The idea is to have a basic app and fill the app with event data. Apart from that the app should have its own logo, color scheme and twitter wall generated through loklak. How can we achieve this goal?

**Comment by batraabhishek** [comment]
Are you looking forward to a native app or an Android app?

*Sent via a really tiny keyboard - please excuse the brevity of the message

**Comment by mariobehling** [comment]
At FOSSASIA many people also suggested a web app. There are pros and cons. What is your preference? What do you suggest?

**Comment by mananwason** [comment]
@mariobehling I think the best idea would be to host a json api online because it gives us flexibility to change the json data provided by google sheets. So, we can take data in sheets and change the json data provided by these sheets.

**Comment by creativepsyco** [comment]
The native app should have a fixed schema defined by JSON API. The API may provide just JSON files. There should be an adapter script which will convert the data from Google Spreadsheets (or a host of other data sources) into JSON format. Probably can use a cron job to trigger the update of the json file or perhaps it can be done manually. The app can sync these files and update at regular intervals to get the most recent data. This way the App will just to have to know which HTTP endpoints to look for to get the data. This is what I believe @leto proposed as well. Later if someone is building a backend to manage the event addition/modification/deletion it can still serve the same JSON schema. The transition would be seamless.

**Comment by championswimmer** [comment]
Yeah creating an API which defines all the data, color scheme etc looks
like the best way forward. Maximum code reusability.

**Comment by Orbiter** [comment]
for the proposed twitter wall, I described the process and a possible API usage in https://github.com/fossasia/open-event/issues/6

**Comment by championswimmer** [comment]
So, to go back to square 1 and redraw the basic plan in a little more
detail, what will be the requirements of the app. Based on current apps we
are working on.

Here is a basic structure I can see.

 > About Event (not there in rp, ots, fossdem, but we should have provision
no ?)
 > Sessions (Day wise, if multi day event)
 ------- details on clicking
 > Speakers
 -------- details on clicking
 > Sponsors
 -------- goto website on clicking
 > Map
 ------- internal layout, if avaialble,
 ------- directions to location
 > Settings
 ------- auto-update data frequency
 > Twitterwall
 ------- based on @event handle or #event hashtag (or configureable?)


So the ">" bullets are sections of app accessible from top level
naviagation which we intend to stick with NavDrawer (?), and ----- are
subsections/details of these sections.
NOTE: I am talking in abstract terms here, from user PoV, and not trying to
figure out what is Activity and what is Fragment etc.


=======================================
  Arnav Gupta (championswimmer)
  LinkedIn <http://in.linkedin.com/in/arnavgupta/> | Web
<http://championswimmer.in> | Blog <http://blog.championswimmer.in> |
Twitter <http://twitter.com/championswimmer> | Facebook
<http://facebook.com/championswimmer> | Github
<http://github.com/championswimmer>

**Comment by leto** [comment]
I agree with @mananwason and @creativepsyco, so we have a clear way forward in terms of implementation. I suggest we focus solely on *features* right now, units of functionality, and worry about layout and UI optimizations when all implementation and functionality is solid. I will create Github Milestones for each unit of functionality.

**Comment by leto** [comment]
Here are all the milestones: https://github.com/fossasia/open-event/milestones

As we create issues for each small bit of functionality, we can organize those into each milestone.

**Comment by leto** [comment]
To summarize the current conversation, we are going to have a framework for creating Android event apps that will use a JSON data file hosted on Github. With this architecture, we can easily add other native apps in the future (iOS/etc) that use the same JSON file. To more concretely answer @mariobehling's question: Each event application will have a github repository with a copy of the open-event code. In that github repo there will be a open-event.json file, which is a configuration file that specifies the logo URL, Twitter accounts/hashtags to show, color scheme and any other configurable options of open event. In addition, this file will contain the JSON data URL that the app pulls the latest schedule from and various other bits. Does that satisfactorily answer your question, @mariobehling ? At this point I believe we need to carve up very specific tasks and see what people can work on indepedently and which things block others from being developed.

**Comment by championswimmer** [comment]
@leto also check https://github.com/fossasia/open-event/issues/7#issuecomment-100032924
Which is like, exactly what you wrote, just in bullet points and numbers :stuck_out_tongue_winking_eye:

**Comment by Orbiter** [comment]
hi @leto nice to meet you here again and work with you!
About your architecture sketch: having a github repository for each instance of the app where they are distinguished only in their configuration sounds really strange. In contrast, different apps could be created during built process by just assigning the build process a configuration vector, like a single url which points to a single json file. Then the apps distinguish only in the given url.

**Comment by mariobehling** [comment]
Hi all, I think we are at a stage where we can get fully started. Let's see some code. The way we are getting started now is great. Let's keep this agile approach and solve questions about UI etc on the way. @leto @Orbiter A goal could be to use a single URL, but for the beginning maybe different repo are useful as the app is probably changing a lot. 

So, thank you all for digging into the depth here. We have a pretty clear plan. Let's get to work. I am closing this issue here and we can continue about specific questions during implementation.

**Comment by championswimmer** [comment]
One last thing, we are starting open-event with a fresh codebase?

The FOSDEM app is good reference but forking that will tie us to some
legacy codebase. For eg Froyo = 1% userbase and reducing. For Froyo many
exceptions and try catch blocks are present on FOSDEM app, we can just
start with fresh app at minSdk 14 (~91% android userbase, and increasing)

**Comment by mananwason** [comment]
I second that @championswimmer. But I'm not sure if I have to start in the open-event repo. @mariobehling @leto Please suggest.

**Comment by mariobehling** [comment]
Great! I think, we figured out that there are different parts to the project. I am not yet completely clear, who will mainly work on what. We can find out together. As a next step we decided to create different repos for the sub-projects. 
* open-event-orga-server (substituting Google form, google docs part and generating JSON files)
* open-event-orga-webclient (frontend parts)
* open-event-webapp (receiving the JSON and generating a nice web app for all platforms)
* open-event-android (receiving the JSON and generating an Android app - similar to
Please help to collect the info we have here for each readme.

**Comment by mariobehling** [comment]
@leto So, we keep this repo to define the milestones etc. for the overall project here (https://github.com/fossasia/open-event/milestones)? But, specific detaild goals we define in the specific repos. Is this the best way, we can work?

**Comment by championswimmer** [comment]
I thought maybe we could have done orga-server and orga-webcliemt in the
same place together.  But I'm good with this to. More modularity always
better.

I'll quickly fill up the respective READMEs today.

Thanks

**Comment by leto** [comment]
@mariobehling yes, those 4 repositories sound like a good start. And I like keeping overall project milestones in open-event. Let's sally forth! :bicyclist: :bicyclist: :bicyclist:
