### ISSUE TITLE
Fix FOSSASIA sample

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event#57]
The FOSSASIA event sample at https://github.com/fossasia/open-event/tree/master/sample/FOSSASIA16 still has a few issues:

* [x] There are a number of speaker duplicates and each speaker entry is related to a talk. Fix: Merge separate speaker entries and ensure a one to multi relationship (one speaker -> several events)
* [x] Change tracks to different colors
* [x] Add ```sponsor_type``` sponsors json in all sample
* [x] Separate name and levels from microlocations name
* [ ] Find any other issues with the sample and fix it.

**Comment by aayusharora** [comment]
> There are a number of speaker duplicates and each speaker entry is related to a talk. Fix: Merge separate speaker entries and ensure a one to multi relationship (one speaker -> several events)
@championswimmer I think you have fixed that? Does it need any other fix.
