### ISSUE TITLE
Check and fix issues/potential issues in all files

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event#61]
**Event.JSON**
There are a few potential inconsistencies in the files, e.g. in this one https://github.com/fossasia/open-event/blob/master/sample/EhealthAfrica/event
* [x] There is a line "background_url": "/images/background.jpg". This line should be moved above "logo" and renamed "background_image".
* [x] Call for papers only seems to have - "closing_datetime": null, - , but not an opening date, which is also necessary.
* [x] Question: Why does the creator need an ID? "creator": { "email": "super_admin@gmail.com", "id": 1
* [x] Description field only seems to have text: Can we/How can we have rich-text/html in this field? (same applies to Call for Speakers and Code of Conduct.
* [x] Version is "0". How is that possible?     "version": {
        "event_ver": 0,
        "microlocations_ver": 0, 
        "sessions_ver": 0, 
        "speakers_ver": 0, 
        "sponsors_ver": 0, 
        "tracks_ver": 0
* [x] Why do social links need to have IDs? What if social links of different events have the same ID number?
            "id": 361, 
            "link": "https://twitter.com/eHealth_africa", 
            "name": "Twitter"
* [x] Please sort the order of the event JSON in the same logical order as the orga server wizard page, e.g. it is illogical to have the follow sorting:
    "latitude": 52.51074, 
    "location_name": "Kemperplatz 1, 10785 Berlin, Germany", 
    "logo": "/images/logo.jpg", 
    "longitude": 13.37233,

**Meta.JSON**
* [x] Why is it localhost? What else do we need meta JSON for? https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/meta
"root_url": "http://localhost:5000/"

**Social Links**
* [x] Why do we need it? All data is already defined in Event JSON.

**Compatibility JSON/API**
* [x] In the app generators we want to use API endpoints and JSON files in the same manner. Currently I see that there is a difference between API and JSON as there are more JSON files than APIs, e.g. Session_Types. How does that work out?

**short_abstract in Session json**
* [x] Right now, the short_abstract is empty for all the [sessions](https://raw.githubusercontent.com/fossasia/open-event/master/sample/FOSSASIA16/sessions).
This is required in issue [https://github.com/fossasia/open-event-android/issues/568](https://github.com/fossasia/open-event-android/issues/568)

**Add address in event.json**
* [x] Right now, only the lat and long of the venue is mentioned, it would be good if we had the address to so that it can be displayed directly in maps. Issue [https://github.com/fossasia/open-event-android/issues/564](https://github.com/fossasia/open-event-android/issues/564)

**Comment by aviaryan** [comment]
> Social Links
 Why do we need it? All data is already defined in Event JSON.

Yes we don't need it. I will fix it. https://github.com/fossasia/open-event-orga-server/issues/2094

**Comment by aviaryan** [comment]
> Description field only seems to have text: Can we/How can we have rich-text/html in this field? (same applies to Call for Speakers and Code of Conduct.

No it can have rich text/html also. The samples have plain text, that's all. You can store rich-text as - 
```
{
"description": "<p>Hi <b>bold</b></p>"
}
```

> Version is "0". How is that possible? "version": { "event_ver": 0, "microlocations_ver": 0, "sessions_ver": 0, "speakers_ver": 0, "sponsors_ver": 0, "tracks_ver": 0

Version is 0 when the event has been just created. If an event without version info in the files is imported, all version info is set to 0. Should I change version infos to some random non-zero values ?

> Why do social links need to have IDs? What if social links of different events have the same ID number? "id": 361, "link": "https://twitter.com/eHealth_africa", "name": "Twitter"

Social links have IDs because they have PUT and DELETE APIs i.e. the server allows to modify/delete single social links. Though the ID is not needed when an event is exported/imported in case of social links but just for completeness that the json reflects the APIs, I have included it too. 

> Why is it localhost? What else do we need meta JSON for? https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/meta "root_url": "http://localhost:5000/"

The event was exported from my local system and hence the root_url is localhost. If the event is next imported into open-event-dev and then further exported, it will have open-event-dev as root_url.

**Comment by mariobehling** [comment]
> The event was exported from my local system and hence the root_url is localhost.

We need a version that is working here for the app generators and the sample files should direct the app generators to the orga server test version. Please help to make things work for the app team.

**Comment by aviaryan** [comment]
> Currently I see that there is a difference between API and JSON as there are more JSON files than APIs, e.g. Session_Types. How does that work out?

As I have explained in [this issue](https://github.com/fossasia/open-event-orga-server/issues/1786#issuecomment-234768569) before, it is not possible to remove session_types json (or put it inside sessions json). 

> In the app generators we want to use API endpoints and JSON files in the same manner.

session_types json does correspond to an API and that is `api/v2/events/ID/sessions/types`.

**Comment by mariobehling** [comment]
> As I have explained in this issue before

Where can this be added to the documentation?

Also regarding documenting the API with swagger, actually we can only read this on a deployed system. How can we read the API documentation without a deployed system?

**Comment by aviaryan** [comment]
> Where can this be added to the documentation?

We can add a FAQ section in import/export docs. 
https://github.com/fossasia/open-event-orga-server/blob/development/docs/IMPORT_EXPORT.md

> How can we read the API documentation without a deployed system?

Swagger generates the documentation from the code. So without building the code, there is no documentation. There are ways to generate PDFs from swagger.json, maybe we can generate one.

**Comment by mariobehling** [comment]
> There are ways to generate PDFs from swagger.json

It would be more suitable to have an API documentation in HTML. Can we save the Swagger HTML pages and store them on github pages?

**Comment by aviaryan** [comment]
> Call for papers only seems to have - "closing_datetime": null, - , but not an opening date, which is also necessary.

closing_datetime was an invalid field and will be removed in https://github.com/fossasia/open-event-orga-server/issues/2120 . The start and end time for CallForPapers is stored in the "call_for_papers" field in event json.

**Comment by aviaryan** [comment]
> It would be more suitable to have an API documentation in HTML. Can we save the Swagger HTML pages and store them on github pages?

Yes it is [possible](https://www.npmjs.com/package/swagger-to-html) to save swagger docs as static HTML pages. Btw, which repo should we store it in ? open-event or new repo ?
We can create a gh-pages branch there and I can write a script that creates the HTML docs from swagger.json and then push it in gh-pages branch so that it is available online.

**Comment by aviaryan** [comment]
> Question: Why does the creator need an ID? "creator": { "email": "super_admin@gmail.com", "id": 1

creator refers to the user who created the event. The user like all other models has an ID. So there is `id` to uniquely identify the user. I agree that it is not needed as email is UNIQUE but keeping IDs is a good practise and everyone does that. 
On a different note, `creator` is not needed for import as the creator is auto-set to the user who imported the event. So should I remove `creator` from the import/export files ?

**Comment by mariobehling** [comment]
> Creator

Please remove the "id", but keep the email. Think of the use case where you have several open event servers and export from one and import to another. You do not want any confusion of which id created it as the systems have different ids.

> Swagger gh-pages.

I think until we have defined an overall documentation strategy, please implement as you described in gh-pages in the orga server (not open-event). It is possible to add this script to travis? Where is the best place to keep the script for future changes? 

Please open relevant issues.

**Comment by aviaryan** [comment]
> Please sort the order of the event JSON in the same logical order as the orga server wizard page, e.g. it is illogical to have the follow sorting: "latitude": 52.51074, "location_name": "Kemperplatz 1, 10785 Berlin, Germany", "logo": "/images/logo.jpg", "longitude": 13.37233,

Currently the json files list the keys in alphabetical order. Should I sort them in a manual order ? Are there any other json files that need to be sorted this way ?

**Comment by mariobehling** [comment]
@aviaryan All content of all JSON files should be sorted in a logical order. If you are unsure, follow the flow of the wizard.

* [ ] Another point is that I see photos are not saved according to names of speakers in the speaker folder for example and there is also an svg file in the speaker folder. Could you export the files as -SpeakergivennameSpeakerfamilyname.png/jpg, please? Please open a dedicated issue.

**Comment by the-dagger** [comment]
@mariobehling @aviaryan I have updated the issue with more points to be fixed, could you please have a look at it?

**Comment by aviaryan** [comment]
@the-dagger 

>  Right now, only the lat and long of the venue is mentioned, it would be good if we had the address to so that it can be displayed directly in maps

The `location_name` is supposed to contain the full address. Eg `Road no 2 C Rajendra Nagar Patna Bihar India 800016` . As the samples were created much eariler than this change, they still have just the location_name as just "Singapore". Feel free to update the samples with full address like "Some building Some location Singapore"  . I can confirm that this format will display directly on google maps. 

> Right now, the short_abstract is empty for all the sessions.

I guess that is because the source jsons didn't have that field themselves. We can add some dummy data there.

**Comment by mariobehling** [comment]
> Please sort the order of the event JSON in the same logical order as the orga server wizard page, e.g. it is illogical to have the follow sorting: "latitude": 52.51074, "location_name": "Kemperplatz 1, 10785 Berlin, Germany", "logo": "/images/logo.jpg", "longitude": 13.37233,

Re-checking on the current version, this still has not been achieved.

A logic order means: Basic info comes first and items that belong together are next to each other, e.g.
* [ ] Start with ID, names and other basic info in JSON files
* [ ] Align items, e.g. longitude and latitude

**Comment by aviaryan** [comment]
@mariobehling I did the change in export module to export in a logical order here. https://github.com/fossasia/open-event-orga-server/pull/2212/
I missed updating the samples. I will update them now. Can you please merge all open PR's because this will require changing whole files and will surely result in merge conflicts.

**Comment by mariobehling** [comment]
Thanks. Merged it.
