### ISSUE TITLE
Define JSON URL the app uses

### ISSUE THREAD

**Issue by leto** [fossasia/open-event#7]
We can have the app use the JSON file directly from Github, and we need to define at least a DEV JSON file and a PRODUCTION JSON file, where we test stuff out on the DEV JSON and then push out vetted changes to the PRODUCTION JSON file, so we don't break everyone's experience using the app.

I propose a ```json/``` directory with a ```dev.json``` and ```prod.json``` in the root directory of each event repository. Does this sound reasonable, @creativepsyco @mananwason ?

**Comment by championswimmer** [comment]
Sounds good to me. 

Also, I was thinking the app should have a json file in it's assets folder too ? So that it comes prepackaged with some data (even if it's some days old - depending on when it was last updated to Play Store), for people opening it first time without internet connection.

**Comment by mananwason** [comment]
@leto I think this is a good idea but I am not sure how would we check if it is a dev or a user. Maybe if we implement google login and for the email id of devs we use dev.json. what are your views @leto

**Comment by leto** [comment]
@championswimmer yes, the APK should come seeded with the latest JSON and only check for updates. @mananwason I think the best way to solve that is have the ability to use a custom JSON URL in the app settings. It will be very useful in the future and allow devs to choose different JSON URLs for testing the live app against various JSON files.

**Comment by mananwason** [comment]
@championswimmer I don't think that's useful if we need to change json file frequently and even if we don't change it, there is no point in having stale data.

**Comment by leto** [comment]
At first, let's use these assumptions:

1) Cache the latest JSON for 1 day up until 3 days before the event
2) Start caching the latest JSON for 3 hrs until the day(s) of the event
3)  Only cache the latest JSON for 1hr or less during the event
4) After the event, go back to once a day for simplicity

**Comment by leto** [comment]
So the app needs to have a configurable setting for the maximum time since the last JSON update and then a function which downloads the latest JSON if the current JSON is too old.

**Comment by leto** [comment]
The app must always show the current version of the JSON, *especially* while downloading the newest version. The FOSSAsia app had a bug where if the update failed, it wiped out all the data and you couldn't view the current JSON data while it was updating.

The latest JSON failing to update should be expected and it is not considered a failure. It should be retried a few times before warning the user that the schedule could not be updated.

**Comment by mananwason** [comment]
@leto I can start building this but all these apps, have a limitation, datadownload function doesn't download the new data again and also the data from database is cleared everyrime app is started. So, we can just implement this function.

**Comment by mananwason** [comment]
Also we can create a version number in spreadsheet, and check everytime we start the app if current version > version in app, we can download latest schedule

**Comment by leto** [comment]
@mananwason yes, :+1: to having a versioned JSON document

**Comment by championswimmer** [comment]
@mananwason, if user downloads app, and then opens it, when internet is not
available, then all he gets is a splashscreen, and some blank fragments.

1-2 days old data is better than that I guess.

**Comment by leto** [comment]
Yes, the app will be seeded with a schedule and always attempt to update it, so it will never be without a schedule.

**Comment by championswimmer** [comment]
The versioning approach seems better than the hourly approach. We can just
check against the timestamp of doc update maybe ? So saves the headache of
the organisers to update json version ?

**Comment by leto** [comment]
@championswimmer perhaps the app can do a HEAD request to the JSON document on github and see it's Modified-Time or ETag/etc ? Then it would know when it's local copy is out of date and organizers wouldn't need to care about version numbers and the app wouldn't need to keep track of version numbers, just one timestamp. Sounds like a :troph:

**Comment by championswimmer** [comment]
Ok, quick summarisation then, 

1. Each event app is hosted in its own github repo.
2. We have the json in app/src/main/assets/data.json. Serves two purpose, while app is built, it is packaged as the seed json, also, can be accessed via raw.github to use as the API endpoint. 
3. When app is compiled in debug mode, Settings screen should have option to chose JSON URL, so we can test new data before pushing to master/stable branch. 
4. App checks last commit to app/src/main/assets/data.json file path, calculates freshness of timestamp, downloads and updates accordingly. 
5. In app, we have the following 3 possible data sources - 
   a) <assets of apk>/data.json
   b) local storage / data.json
   c) github repo / data.json
6. The algorithm goes like this 
 > Check for internet, if not connected fallback to (b), if (b) file not exists fallback to (a)
 > If connected, check timestamp, compare with (b), if file (b) not exists, compare with (a).
 > If newer, download and overwrite (b)

**Comment by leto** [comment]
@championswimmer that is a great summary. Please feel free to start implementing that in code! The bonding period is almost over and the flood gates of code need some time to open fully....

**Comment by creativepsyco** [comment]
Yes! Sounds good @leto @championswimmer @mananwason! Thats what I had in mind. Great Summary! However, I don't think the app should be checking for the last commit. That would tie it to the Version Control system. To me version number sounds good enough. For Pre-loading, you can pass the JSON in the app raw asset folder or you can directly provide a SQLite Database which you can copy into the app private folder during the first start of the app. That way your old unsynced data will be available always before anything happens, after that your the update logic will take care of the rest. To know if data has changed there are methods like `ETag`, version number etc, update time stamp etc.

**Comment by mananwason** [comment]
@championswimmer Nice summary but I agree with @creativepsyco. We should not check based on last commit, it can create conflicts. Version number is an easy and fool proof way. Why not use it ?

**Comment by leto** [comment]
Yes, let's change "App checks last commit to app/src/main/assets/data.json file path, calculates freshness of timestamp," to "App checks freshness of timestamp" and use whichever method is simple to implement and works at least 80% of the time.
