### ISSUE TITLE
Update samples with speaker images having their names

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event#70]
https://github.com/fossasia/open-event-orga-server/issues/2169

Now that the feature to export speaker images with their names as filenames is done, we should update the samples to reflect the same. 
Eg > Change speakers/photo1.jpg to speakers/MattBlanc_1.jpg 

https://github.com/fossasia/open-event/issues/61#issuecomment-239312104
> Could you export the files as -SpeakergivennameSpeakerfamilyname.png/jpg, please? Please open a dedicated issue.

**Comment by the-dagger** [comment]
@aviaryan also many speaker don't have their images. 
Will you be working on that too?

**Comment by aviaryan** [comment]
@the-dagger No. this issue doesn't involve that.
