### ISSUE TITLE
Bug in Sponsor level

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event#74]
@mananwason  After your last PR the sponsor levels https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/sponsors#L14 are added in Fossasia sample which seems integers. They should be considered as strings like we do in OTS16 repo  https://github.com/fossasia/open-event/blob/master/sample/OTS16/sponsors#L14

**Comment by mananwason** [comment]
@aayusharora @mariobehling Mentioned that levels are supposed to be integers that can be used for sorting.

**Comment by aayusharora** [comment]
@mananwason The form in which they are available in OTS16 https://github.com/fossasia/open-event/blob/master/sample/OTS16/sponsors#L14 are used as sorting as well. I have made them in Fossasia sample repo  #75 to maintain consistency.

**Comment by mananwason** [comment]
I agree @aayusharora but @mariobehling Said that levels are ints. They can obviously be changed to any of strings and int on the client side but we need to follow a format we expect from the server. So I think @mariobehling or someone from the server can clarify this.

**Comment by aviaryan** [comment]
@mananwason @aayusharora  The Database model of sponsor has level as string, and they have been like this for a long time now.

**Comment by championswimmer** [comment]
@aviaryan to be clear, the format is string, but the values will be integers right ? 

(because sorting 'one' and 'two' is different from sorting '1' and '2' ;) )

**Comment by aviaryan** [comment]
@championswimmer Yes. Orga Server UI has a NumberPicker for the field level and it doesn't allow strings so you can be sure that it will have integers.

**Comment by championswimmer** [comment]
Thanks Avi :)
