### ISSUE TITLE
create a project on code.google.com for Google Maps API 

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event#8]

**Comment by championswimmer** [comment]
Created the project. Right now myself and @mariobehling are owners (sent an invite to him to be owner). 
Others please mail me your Google/Gmail account id to championswimmer@gmail.com and I'll add you.

**Comment by mananwason** [comment]
Hi @championswimmer why do we need this?

**Comment by championswimmer** [comment]
Google Maps API can be used only with an authorised app.
We have to make a project on Google Code for it, and submit app id and sha1 of keystore.

**Comment by leto** [comment]
Google Code is shutting down. Is that documentation current?

**Comment by mananwason** [comment]
@championswimmer You just need a key for maps api that's all, We have a maps api already in use in our apps and It has been set using just the key. So I don't get the point to create a project?

**Comment by creativepsyco** [comment]
@mananwason the project also needs the signature of the APK as well. I think should probably have 1 single project on google API console https://code.google.com/apis/console/ and someone should manage it, and request for stuff to be done in it, I think @mariobehling can do it and add other people into the project from time to time. We should probably use the same project if we were doing OAuth2 signup or Google Drive/ Google+ integrations. No point in creating multiple projects for multiple things.

**Comment by championswimmer** [comment]
I have created the project.  Have sent Mario and Duke owner invites. To
Manan too.

**Comment by championswimmer** [comment]
The Ots15 app has the API keys.
The maps are already working on that.
