### ISSUE TITLE
Add .json to the samples

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event#83]
Since we are directly copying the json files from the [sample zip](https://github.com/fossasia/open-event/blob/master/sample/EhealthAfrica.zip) into the assets folder of the android app , the samples need to have `.json` so as to be correctly recognised as json files.
@mariobehling @aviaryan Could you please provide your views on this?

**Comment by aviaryan** [comment]
@the-dagger The reason .json was removed was because web app team ( @championswimmer @aayusharora ) had some issues with it. If they are fine with it, we can do it.

**Comment by championswimmer** [comment]
@the-dagger the app can read the files even if they are not having .json extension

**Comment by championswimmer** [comment]
@the-dagger the reason we dropped .json is that github raw API can be used to emulate orga-server api. not possible if the .json extensions exist.

**Comment by the-dagger** [comment]
@championswimmer Thanks for the info.
I'll try to find a way around to fix this up on the backend server.

**Comment by the-dagger** [comment]
@mananwason

**Comment by mananwason** [comment]
@the-dagger @championswimmer is right. It's just the current implementation read json files with '.json' extension. we can change that if required.
