### ISSUE TITLE
Proper Time Zone handling

### ISSUE THREAD

**Issue by Orbiter** [fossasia/open-event#9]
These are code pieces where you must consider the time zone:

- the event description json must declare in which time zone the event happens
- the event description json must declare the time zone for the given event times (may be given in GMT)
- the mobile device has a time zone (conference visitors tend to come from time zones different from the event time zone)

I believe that event dates shall be displayed in the event app according to the local time of the event. But that time may not be the same as the time zone of the device. The app shall be able to handle that.

**Comment by batraabhishek** [comment]
@Orbiter Yup ! Even I faced issues while converting events schedule to iCal file. May be we can use something like 2013-04-12T13:38:48+02:00 ... DateTime format   with timezone. With timezone already present in DateTime for each event. We can auto convert it, while showing or setting a alarm notification for that event. Check http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html for refer. :)

**Comment by Orbiter** [comment]
yes, 2013-04-12T13:38:48+02:00 would be a proper time format, but people tend to write "2013-04-12", "2013-04-12 13:38" and maybe forget completely about the time zone. In loklak I use the joda library, http://joda-time.sourceforge.net/apidocs/org/joda/time/format/ISODateTimeFormat.html dateOptionalTimeParser() handles them all.

Furthermore, we need a representation of the time zone only. I use the timezoneOffset, which javascript produces with http://www.w3schools.com/jsref/jsref_gettimezoneoffset.asp
Thats a single integer (minutes) which also includes the current Daylight Saving. Germany is currently in timezoneOffset=-120, but in winter it's in timezoneOffset=-60.

Using the timezoneOffset, you can
- use all times as 'local time' (one offset applies to all)
- write down all times in a short and human-readyble form
- compare the device time zone with the event time zone easily

**Comment by leto** [comment]
TZ-aware datetimes should be stored internally as UTC offsets and rendered to the user in whichever format they would like. Anything else leads to insanity. And I completely agree with @Orbiter's recommendations.

**Comment by championswimmer** [comment]
No one will enter the string by hand. On the flask-admin console we have a
date time picker. Similarly, in the app I have written a ISO8601date.java
class that converts ISO8601 strings to Calendar objects and vice versa.

A full ISO8601 string in the yyyy-MM-ddTHH:mm:ssZ format is the only way to
save times in "absolute" manner. i.e. the string completely defines a time,
without being dependent on anything or being relative to anything.

**Comment by championswimmer** [comment]
I mean to summarise

1. In the server, the organiser will use a picker to enter year, month,
time from a spinner, so he won't commit mistake.
2. In the database/json time is always in ISO8601 format
3. In app, date is shown as per the user's language/region preference. We
will show it according to his locale. So americans get 5/15 for 15th May,
Indians get 15/5 for 15th May.

I hope that sounds like a preferable choice to everyone ?

**Comment by championswimmer** [comment]
We are using ISO8601 already. So let's close this issue ?
